<?php namespace SuperPowers\Controller;

class News extends SuperTypeController {
	public function getDefinition()
	{
		return array(
			'groups' => array(
				'info' => $this->create->group('info', 'Info', array(
					'properties' => array(
						$this->create->property('image', 'image', array(
							'label' => 'Image',
							'size' => array(
								'default' => '200x112'
							)
						))
					)
				))
			)
		);
	}

	public function view(){

		$post = get_post($this->postId);

		return array(
			'title' => $post->post_title,
			'content' => $this->post->content($post->ID),
			'date' => $this->post->date($this->postId),
			'tags' => array(),
			'authorId' => $post->post_author
		);
	}

	public function listView()
	{
		$title = 'Nyheter';
		$posts = array();
		$game = null;

		// Specific game news
		if($this->postId) {
			$game = get_post($this->postId);
			$title = "Nyheter | {$game->post_title}";
			$posts = $this->news->getGameNews($game->ID);
		}

		$args = array(
			'postId'    => $this->postId,
			'title'     => $title,
			'view'      => 'news',
			'posts'     => $this->news->format($posts),
			'gameId'    => $game->ID
		);

		$this->html->view('news.list', $args);
		exit();
	}

	public function save($args)
	{
		parent::save($args); // TODO: Change the autogenerated stub
	}


}