<?php namespace SuperPowers\Controller;

class Page extends SuperTypeController
{
	public function getDefinition()
	{
		return array(
			'groups' => array()
		);
	}

	public function save($args)
	{
		parent::save($args); // TODO: Change the autogenerated stub
	}
}