<?php namespace SuperPowers\Controller\Page;

use SuperPowers\Controller\Page;

class Community extends Page {

	public function getDefinition()
	{
		return array(
			'groups' => array()
		);
	}

	public function save($args)
	{
		parent::save($args); // TODO: Change the autogenerated stub
	}

	protected function view()
	{
		return array(
			'activities' => $this->activity->getList(array('feed', 'game')),
			'url' => $this->user->url(),
			'image' => $this->user->image($this->user->id()),
			'userId' => $this->user->id()
		);
	}
}