<?php namespace SuperPowers\Controller\Page;

use SuperPowers\Controller\Page;

class Front extends Page {

	public function getDefinition()
	{
		return array(
			'groups' => array()
		);
	}

	public function save($args)
	{
		parent::save($args); // TODO: Change the autogenerated stub
	}

	protected function view()
	{
		return array(
			'posts' => $this->news->format($this->news->recent())
		);
	}
}