<?php namespace SuperPowers\Controller\Page;

use SuperPowers\Controller\Page;

class Video extends Page {

	public function getDefinition()
	{
		return array(
			'groups' => array()
		);
	}

	public function save($args)
	{
		parent::save($args); // TODO: Change the autogenerated stub
	}

	protected function view()
	{
		global $wp_query;

		$latest = $this->video->latestVideo();

		$category = null;
		$search = null;
		$page = 1;

		$url = get_permalink($this->postId);

		if(!empty($_GET['category'])) {
			$category = $_GET['category'];
			$categoryTerm = get_term_by('slug', $category, 'video-category');
			$url = add_query_arg('category', $category, $url);
		}

		if(!empty($_GET['search'])) {
			$search = $_GET['search'];
			$url = add_query_arg('search', $search, $url);
		}

		if(!empty($_GET['page'])) {
			$page = $_GET['page'];
			$url = add_query_arg('page', $page, $url);
		}

		if(!empty($wp_query->query_vars['page'])) {
			$page = $wp_query->query_vars['page'];
			$url = add_query_arg('page', $page, $url);
		}

		$categories = $this->video->getCategories($this->postId, $category);

		$all = array(
			'link' => get_permalink($this->postId),
			'title' => 'Alla videos',
			'active' => (empty($category))
		);

		array_unshift($categories, $all);

		/** @var \WP_Query $query */
		$query = $this->video->get(12, $page, $category, $search);

		$categoryTitle = (empty($category)?'Senaste videos': "Kategori: {$categoryTerm->name}");

		if(!empty($search)) {

			$categoryTitle = "Söker efter: <i>{$search}</i>";
			if(!empty($category)) {
				$categoryTitle .= ", Kategori: <i>{$categoryTerm->name}</i>";
			}
		}

		return array(
			'latestVideo'   => $latest,
			'posts'         => $this->news->format($query->get_posts()),
			'title'         => 'Videos',
			'categories'    => $categories,
			'category'      => $categoryTitle,
			'search'        => $search,
			'categorySlug'  => $category,
			'pagination'    => $this->pagination->create($query, $url),
			'hash'          => '#videos'
		);
	}
}